-- 코드를 입력하세요
SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES * A.PRICE) AS TOTAL_SALES
FROM BOOK AS A
JOIN AUTHOR AS B
ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES AS C
ON A.BOOK_ID = C.BOOK_ID
AND SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY 1, 3
ORDER BY 1 ASC, 3 DESC