### 1. 로그인
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
client.global.set("accessToken", response.body.accessToken)
client.global.set("refreshToken", response.body.responseToken)
 %}

### 2. home 조회
GET {{host}}/auth/home
Authorization: Bearer {{accessToken}}
