rootProject.name = "jwt"
include("application:app-auth")
include("application:app-food")
include("core")
include("core-jpa")
include("domains:domain-user")
include("domains:domain-user-auth")
include("domains:domain-food")
include("modules:inmemory-jpa-repository")
include("modules:restdocs-kotlin-dsl")
