package com.keunwon.algorithm.baekjoon

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

internal class Problem16954Test : StringSpec({
    "case_01" {
        val map = """
            ........
            ........
            ........
            ........
            ........
            ........
            ........
            ........
        """.trimIndent().split(System.lineSeparator()).map { it.toCharArray() }.toTypedArray()

        val actual = Problem16954().solution(map)

        actual shouldBe 1
    }

    "case_02" {
        val map = """
            ........
            ........
            ........
            ........
            ........
            ........
            ##......
            ........
        """.trimIndent().split(System.lineSeparator()).map { it.toCharArray() }.toTypedArray()

        val actual = Problem16954().solution(map)

        actual shouldBe 0
    }

    "case_03" {
        val map = """
            ........
            ........
            ........
            ........
            ........
            .#......
            #.......
            .#......
        """.trimIndent().split(System.lineSeparator()).map { it.toCharArray() }.toTypedArray()

        val actual = Problem16954().solution(map)

        actual shouldBe 0
    }

    "case_04" {
        val map = """
            ........
            ........
            ........
            ........
            ........
            .#######
            #.......
            ........
        """.trimIndent().split(System.lineSeparator()).map { it.toCharArray() }.toTypedArray()

        val actual = Problem16954().solution(map)

        actual shouldBe 1
    }

    "case_05" {
        val map = """
            ........
            ........
            ........
            ........
            #.......
            .#######
            #.......
            ........
        """.trimIndent().split(System.lineSeparator()).map { it.toCharArray() }.toTypedArray()

        val actual = Problem16954().solution(map)

        actual shouldBe 0
    }
})
