spring:
  thymeleaf:
    cache: false
  webflux:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 8080
logging:
  level:
    web: debug
    org.springframework.data: trace
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/manage"
      path-mapping:
        {
          loggers: logs
        }