---
# tasks file for nginx
- name: Install Nginx
  yum:
    pkg: nginx
    state: installed
    update_cache: yes
  notify:
    - Restart Nginx
  become: True

# - name: Copy Nginx default.conf
#   template:
#     src: template/default.j2
#     dest: /etc/nginx/sites-available/default
#     owner: root
#     group: root
#     mode: 0644
#   notify:
#     - Restart nginx
#   become: True
