-- 코드를 입력하세요
SELECT 	A.USER_ID,
		A.NICKNAME,
        CONCAT(A.CITY, ' ', A.STREET_ADDRESS1, ' ', A.STREET_ADDRESS2) AS `전체주소`,
        CONCAT(LEFT(TLNO, 3), '-', SUBSTR(TLNO, 4, 4), '-', RIGHT(TLNO, 4)) AS `전화번호`
FROM USED_GOODS_USER AS A
WHERE A.USER_ID IN (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD 
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
)
ORDER BY 1 DESC