---
server:
  port: 8080

spring:
  application:
    name: application-food
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:app-food;MODE=MYSQL;NON_KEYWORDS=USER
      username: sa
      password:
  jpa:
    open-in-view: false
    generate-ddl: true
    database: h2
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
