version: "3.7"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: sql-cookbook
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      - MYSQL_ROOT_PASSWORD=root
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    deploy:
      resources:
        limits:
          memory: "5G"
          cpus: "0.25"
