version: '3.7'

services:
  controller:
    image: ngrinder/controller
    container_name: ngrinder
    environment:
        - TZ=Asia/Seoul
    ports:
        - '8881:80'
        - '16001:16001'
        - '12000-12009:12000-12009'
    volumes:
      - ./ngrinder-tmp:/opt/ngrinder-controller
    sysctls:
      - net.core.somaxconn=65000
    restart: unless-stopped
  agent-1:
    image: ngrinder/agent
    container_name: agent-1
    environment:
      - TZ=Asia/Seoul
    links:
      - controller
    restart: unless-stopped
  agent-2:
    image: ngrinder/agent
    container_name: agent-2
    environment:
      - TZ=Asia/Seoul
    links:
      - controller
    restart: unless-stopped
