version: '3.7'

services:
  ngrinder-controller:
    image: ngrinder/controller
    container_name: ngrinder
    environment:
        - TZ=Asia/Seoul
    ports:
        - '8881:80'
        - '16001:16001'
        - '12000-12009:12000-12009'
    volumes:
      - ./ngrinder-tmp:/opt/ngrinder-controller
    sysctls:
      - net.core.somaxconn=65000
    networks:
      - ngrinder-net 
  agent-1:
    image: ngrinder/agent
    container_name: agent-1
    environment:
      - TZ=Asia/Seoul
    links:
      - ngrinder-controller
    networks:
      - ngrinder-net 
        

networks:
  ngrinder-net:
    driver: bridge
