---
spring:
  application:
    name: sre-mvc
  profiles:
    include: core, mvc
  task:
    scheduling:
      pool:
        size: 10
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080
