-- 코드를 입력하세요
SELECT A.MEMBER_NAME, B.REVIEW_TEXT, B.REVIEW_DATE
FROM MEMBER_PROFILE AS A
JOIN REST_REVIEW AS B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE B.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY 3 ASC, 2 ASC