version: '3.9'

services:
  nginx:
    image: nginx:1.23.2
    container_name: nginx
    restart: unless-stopped
    ports: 
      - 80:80
      - 433:433
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./stream.conf.d:/etc/nginx/stream.conf.d
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
