---
- name: nginx docker-compose 업로드
  hosts: nginx
  vars:
    - FORCE_WRITE: '{{ FORCE | default(false) }}'
  tasks:
    - stat:
        path: create-nginx-compose.yml
      register: path_output
    - copy:
        src: create-nginx-compose.yml
        dest: /home/nginx/
        mode: 0766
      when: not path_output.stat.exists or FORCE_WRITE
    - shell: 'docker-compose -f create-nginx-compose.yml down &&
    docker-compose -f create-nginx-compose.yml up -d'
      when: FORCE_WRITE

- name: nginx 설정파일 업로드
  hosts: nginx
  tasks:
    - copy:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        mode: 0766
      loop:
        - { src: './nginx.conf', dest: '/home/nginx' }
        - { src: './conf.d', dest: '/home/nginx' }
        - { src: './stream.conf.d', dest: '/home/nginx' }
