server:
  port: 8081
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 100
    max-connections: 8192
logging:
  level:
    root: info
    com.myshop: debug
    com.zaxxer.hikari.HikariConfig: debug
    #org.springframework.security: debug
    #org.hibernate.type.descriptor.sql: trace

spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  jpa:
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test-shop;MODE=MySQL
    username: sa
    password:
    hikari:
      maximum-pool-size: 15
      connection-timeout: 10000
  sql:
    init:
      mode: always
      platform: local
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false