server:
  port: 8081
logging:
  level:
    root: info
    com.myshop: debug
    #org.springframework.security: debug
    #org.hibernate.type.descriptor.sql: trace

spring:
  jpa:
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test-shop;MODE=MySQL
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
  sql:
    init:
      mode: always
      platform: local

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
